name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have read the documentation and examples
          required: true
        - label: This feature would benefit the broader community, not just my specific use case
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: |
        Currently, when working with MCP servers, I need to...
        This is problematic because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution to the problem
      placeholder: |
        I would like to be able to...
        This could work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or workarounds have you considered?
      placeholder: |
        I considered...
        But this doesn't work because...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - API Enhancement
        - New Transport Support
        - Configuration Management
        - Error Handling
        - Performance Improvement
        - Developer Experience
        - Documentation
        - Testing/Mocking
        - Monitoring/Observability
        - Security
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my use case
        - Critical - Can't use the library without this
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help
      placeholder: |
        In my application, I need to...
        This feature would allow me to...
        The benefit would be...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: Proposed API Design
      description: If you have ideas about the API design, share them here
      render: go
      placeholder: |
        // Example API design
        adapter.NewFeature(options...)
        
        // Or configuration changes
        config := &Config{
          NewOption: "value",
        }

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Show how you would use this feature
      render: go
      placeholder: |
        // Example usage
        adapter, err := mcpadapter.New(
          mcpadapter.WithNewFeature(options),
        )

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes?
      options:
        - label: This feature would require breaking changes to the API
          required: false
        - label: This feature can be implemented without breaking changes
          required: false
        - label: I'm not sure about breaking changes
          required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, share them
      placeholder: |
        This could be implemented by...
        The main challenges might be...
        It would need to integrate with...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute to implementing this feature?
      options:
        - label: I would like to work on implementing this feature
          required: false
        - label: I can help with testing this feature
          required: false
        - label: I can help with documentation for this feature
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references
      placeholder: |
        Related projects that have this feature...
        Links to relevant documentation...
        Screenshots or mockups...